# Generated by Django 4.1 on 2023-09-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_group_page_rename_cid_replycomment_rid_pagepost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagepost',
            options={'verbose_name_plural': 'Page Post'},
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
