# Generated by Django 4.1 on 2023-09-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pagepost_options_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='visibility',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Only Me', 'Only Me')], default='everyone', max_length=10),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='visibility',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Only Me', 'Only Me')], default='everyone', max_length=10),
        ),
        migrations.AlterField(
            model_name='page',
            name='visibility',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Only Me', 'Only Me')], default='everyone', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagepost',
            name='visibility',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Only Me', 'Only Me')], default='everyone', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Only Me', 'Only Me')], default='Everyone', max_length=100),
        ),
    ]
